# Generated by Django 2.0 on 2018-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skype',
            field=models.CharField(max_length=64, null=True, verbose_name='Skype'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(max_length=64, null=True, verbose_name='Telegram'),
        ),
    ]
